version: '3.7'
services:
  arangodb_db_container:
    image: arangodb:latest
   # command: --database.auto-upgrade
    container_name: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
      - ./:/var/www/html
  event_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: event-service
    container_name: eventsvc
    command: /bin/sh -c "sleep 5; /usr/app"
    environment: 
      - DB_ADDRESS=http://arangodb:8529
    depends_on:
      - arangodb_db_container
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
